export const systemPrompt = `You are an expert at crafting text-to-video generation prompts for AI video models (specifically Wan 2.1/2.2 via ComfyUI). You understand how to describe scenes, camera movements, lighting, and visual styles in a way that produces high-quality AI-generated video.

Guidelines:
- Be specific about visual elements: subject, action, setting, lighting, camera angle
- Include camera movement descriptions (pan, zoom, dolly, static)
- Specify visual style (cinematic, documentary, animated, etc.)
- Describe lighting conditions (golden hour, studio, natural, dramatic)
- Keep prompts concise but descriptive (1-3 sentences)
- Avoid abstract concepts — describe what should be SEEN
- Include color palette suggestions when relevant
- Mention aspect ratio and composition guidance
- Focus on a single coherent scene per prompt
- Avoid negative prompts or what NOT to show

Output a single, optimized video generation prompt.`

export function buildUserPrompt(
  topic: string,
  script: string,
  resolution: string
): string {
  const isVertical = (() => {
    const parts = resolution.split('x').map(Number)
    return parts.length === 2 && parts[0] < parts[1]
  })()

  const orientation = isVertical ? 'vertical (portrait, 9:16)' : 'horizontal (landscape, 16:9)'

  return `Topic: ${topic}
Video Orientation: ${orientation}
Resolution: ${resolution}

Based on the following video script, create a single optimized text-to-video prompt for the Wan 2.1 AI video generation model.

--- SCRIPT ---
${script.substring(0, 4000)}
--- END SCRIPT ---

Create ONE video generation prompt that:
1. Captures the main visual theme of the video
2. Describes a specific, visually compelling scene
3. Includes camera movement (e.g., "slow dolly forward", "aerial pan")
4. Specifies lighting and atmosphere
5. Mentions visual style (cinematic, documentary, etc.)
6. Is optimized for ${orientation} composition
7. Is 1-3 sentences long
8. Focuses on what can be realistically generated by an AI video model

Output ONLY the prompt text, nothing else. No explanations, no formatting, just the raw prompt.`
}
